### PR TITLE
feat: add option `closing-bracket-newline` for html

### PR DESCRIPTION
**Pull request by zhaojjiang**
# Description

#1707

- [html-closing-bracket-newline]

New Option for HTML: `closing-bracket-newline`
- this option decide whether add newline before tag's closing bracket or not
- it only worked when tag already has wrapped attributes
- so this option can be combined with option `wrap-attributes`

# Before Merge Checklist 
These items can be completed after PR is created.

(Check any items that are not applicable (NA) for this PR)

- [x] JavaScript implementation
- [ ] Python implementation (NA if HTML beautifier)
- [x] Added Tests to data file(s)
- [x] Added command-line option(s) (NA if
- [x] README.md documents new feature/option(s)

### CODE REVIEW

**Comment by bitwiseman** [comment]
@zhaojjiang 
That's for the PR.  I'm not sure I understand why a new option is needed.  
The issue talks about fixing `"wrap-attributes": "preserve"`.

**Comment by zhaojjiang** [comment]
> @zhaojjiang That's for the PR. I'm not sure I understand why a new option is needed. The issue talks about fixing `"wrap-attributes": "preserve"`.

yes, the issue's title is about `wrap-attributes`, but newline before closing bracket is mentioned:

> Please fix "preserved" or add a new option for keeping the line break before the closing angle bracket.

> I also need this feature for preserve-aligned please!

so I add a new option to add a newline, and keep wrap-attributes option working as before

**Comment by zhaojjiang** [comment]
> @zhaojjiang That's for the PR. I'm not sure I understand why a new option is needed. The issue talks about fixing `"wrap-attributes": "preserve"`.

We can ignore that issue mentioned above, I can edit and remove it from this pr.

I really think this new option `closing-bracker-newline` is helpful.

**Comment by zhaojjiang** [comment]
with unnecessary format change, maybe another pr

**Pull request closed without merging**
